### ISSUE TITLE
App crashing on Nexus 6 API 18

### ISSUE THREAD

**Issue by abs51295** [systers/PCSA-Android#409]
Application is crashing on launch when ran on Nexus 6 with API 18 and gradle plugin 1.2.3 and `compileSdkVersion 25` and `buildToolsVersion '25.0.2'`.

![screenshot_20170306-112750](https://cloud.githubusercontent.com/assets/13438222/23598727/4a57e7d8-0262-11e7-9c5f-c6f43892ea77.png)

![screenshot_20170306-113126](https://cloud.githubusercontent.com/assets/13438222/23598739/5a4ab8be-0262-11e7-921a-2f48ed9e5bf3.png)

![screenshot_20170306-113141](https://cloud.githubusercontent.com/assets/13438222/23598743/60bdbafc-0262-11e7-9968-dedd627cc5dc.png)

Here is the Crash Log:

`E/VdcInflateDelegate: Exception while inflating <vector>
                      org.xmlpull.v1.XmlPullParserException: Binary XML file line #17<vector> tag requires viewportWidth > 0
                          at android.support.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:720)
                          at android.support.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:653)
                          at android.support.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:615)
                          at android.support.v7.widget.AppCompatDrawableManager$VdcInflateDelegate.createFromXmlInner(AppCompatDrawableManager.java:734)
                          at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:367)
                          at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:197)
                          at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
                          at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:711)
                          at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:195)
                          at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81)
                          at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:131)
                          at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:151)
                          at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:31)
                          at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:55)
                          at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:205)
                          at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185)
                          at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:519)
                          at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
                          at com.peacecorps.pcsa.MainActivity.onCreate(MainActivity.java:113)
                          at android.app.Activity.performCreate(Activity.java:5133)
                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
                          at android.app.ActivityThread.access$600(ActivityThread.java:141)
                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                          at android.os.Handler.dispatchMessage(Handler.java:99)
                          at android.os.Looper.loop(Looper.java:137)
                          at android.app.ActivityThread.main(ActivityThread.java:5103)
                          at java.lang.reflect.Method.invokeNative(Native Method)
                          at java.lang.reflect.Method.invoke(Method.java:525)
                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                          at dalvik.system.NativeStart.main(Native Method)
D/AndroidRuntime: Shutting down VM
W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xb0fdc678)
E/AndroidRuntime: FATAL EXCEPTION: main
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.peacecorps.pcsa/com.peacecorps.pcsa.MainActivity}: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2211)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
                      at android.app.ActivityThread.access$600(ActivityThread.java:141)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:137)
                      at android.app.ActivityThread.main(ActivityThread.java:5103)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:525)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052
                      at android.content.res.Resources.loadDrawable(Resources.java:2096)
                      at android.content.res.Resources.getDrawable(Resources.java:695)
                      at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:374)
                      at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:202)
                      at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
                      at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:711)
                      at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:195)
                      at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81)
                      at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:131)
                      at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:151)
                      at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:31)
                      at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:55)
                      at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:205)
                      at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185)
                      at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:519)
                      at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
                      at com.peacecorps.pcsa.MainActivity.onCreate(MainActivity.java:113)
                      at android.app.Activity.performCreate(Activity.java:5133)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261) 
                      at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                      at android.os.Looper.loop(Looper.java:137) 
                      at android.app.ActivityThread.main(ActivityThread.java:5103) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:525) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                      at dalvik.system.NativeStart.main(Native Method) 
                   Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
                      at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:897)
                      at android.graphics.drawable.Drawable.createFromXml(Drawable.java:837)
                      at android.content.res.Resources.loadDrawable(Resources.java:2092)
                      at android.content.res.Resources.getDrawable(Resources.java:695) 
                      at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:374) 
                      at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:202) 
                      at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190) 
                      at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:711) 
                      at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:195) 
                      at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81) 
                      at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:131) 
                      at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:151) 
                      at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:31) 
                      at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:55) 
                      at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:205) 
                      at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185) 
                      at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:519) 
                      at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71) 
                      at com.peacecorps.pcsa.MainActivity.onCreate(MainActivity.java:113) 
                      at android.app.Activity.performCreate(Activity.java:5133) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261) 
                      at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                      at android.os.Looper.loop(Looper.java:137) 
                      at android.app.ActivityThread.main(ActivityThread.java:5103) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:525) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                      at dalvik.system.NativeStart.main(Native Method) 
`

Yes I would like to work on the issue :)

**Comment by sandarumk** [comment]
Can you go through all the versions and list out which are the versions the app crashes and which are the versions it does not? It will be easier rather than opening us issues for separate versions.

**Comment by abs51295** [comment]
@sandarumk For sure :)

**Comment by abs51295** [comment]
@sandarumk It's crashing on API 18 and API 19.
